In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from IPython.display import display # Allows the use of display() for DataFrames
# Show matplotlib plots inline (nicely formatted in the notebook)
%matplotlib inline

In [2]:
# Load preprocessed datasets
df_train = pd.read_pickle('train_2.pickle')
df_test = pd.read_pickle('test_2.pickle')

print "df_train has {} rows and {} columns.".format(*df_train.shape)
print "df_test set has {} rows and {} columns.".format(*df_test.shape)

display(df_train.head())
display(df_test.head())

df_train has 188318 rows and 132 columns.
df_test set has 125546 rows and 131 columns.

,id,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,...,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14,loss
0,1,0,1,0,1,0,0,0,0,1,...,1.108703,-0.867842,-0.985656,1.135665,1.624031,0.475088,0.585261,1.366916,1.005421,2213.18
1,2,0,1,0,0,0,0,0,0,1,...,-0.112007,-0.097665,0.782614,-0.756426,-0.216695,-0.685376,-0.523712,0.711471,-0.813262,1283.60
2,5,0,1,0,0,1,0,0,0,1,...,-1.015334,-1.040286,-1.284374,-1.615149,-0.938231,-0.441743,-0.483861,-1.788073,1.175793,3005.09
3,10,1,1,0,1,0,0,0,0,1,...,-0.101198,-0.418318,-0.843683,-1.019755,-0.184879,-0.746428,-0.783747,0.687649,0.637600,939.85
4,11,0,1,0,1,0,0,0,0,1,...,-1.865655,-1.719031,-1.602838,-2.060148,-1.764897,-1.548267,-1.571249,-1.335213,-0.079009,2763.85

,id,cat1,cat2,cat3,cat4,cat5,cat6,cat7,cat8,cat9,...,cont5,cont6,cont7,cont8,cont9,cont10,cont11,cont12,cont13,cont14
0,4,0,1,0,0,0,0,0,0,1,...,-0.467026,-2.970429,-3.854536,-0.651221,-5.224355,-3.364295,-2.447742,-2.468786,-3.343957,-1.047484
1,6,0,1,0,1,0,0,0,0,1,...,-0.467026,-2.970429,-3.854536,-0.651221,-5.224355,-3.364295,-2.447742,-2.468786,-3.343957,-1.047484
2,9,0,1,0,1,1,0,1,0,1,...,-0.467026,-2.970429,-3.854536,-0.651221,-5.224355,-3.364295,-2.447742,-2.468786,-3.343957,-1.047484
3,12,0,0,0,0,1,0,0,0,0,...,-0.467026,-2.970429,-3.854536,-0.651221,-5.224355,-3.364295,-2.447742,-2.468786,-3.343957,-1.047484
4,15,1,0,0,0,0,1,0,0,0,...,-0.467026,-2.970429,-3.854536,-0.651221,-5.224355,-3.364295,-2.447742,-2.468786,-3.343957,-1.047484

In [3]:
# Split dataset into train and test
from sklearn.model_selection import train_test_split

features = df_train.drop(['loss', 'id'], axis=1, inplace=False)
target = df_train['loss']

X_train, X_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=42)

print "Training set has {} samples.".format(X_train.shape[0])
print "Testing set has {} samples.".format(X_test.shape[0])

Training set has 150654 samples.
Testing set has 37664 samples.

In [11]:
# Train model
from time import time
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import ElasticNet
from sklearn.linear_model import BayesianRidge
from sklearn.linear_model import ARDRegression

def train_classifier(clf, X_train, y_train):
    ''' Fits a classifier to the training data. '''
    
    # Start the clock, train the classifier, then stop the clock
    start = time()
    clf.fit(X_train, y_train)
    end = time()
    
    # Print the results
    print "Trained model in {:.4f} seconds".format(end - start)

def predict_labels(clf, features, target):
    ''' Makes predictions using a fit classifier based on F1 score. '''
    
    # Start the clock, make predictions, then stop the clock
    start = time()
    y_pred = clf.predict(features)
    end = time()
    
    # Print and return results
    print "Made predictions in {:.4f} seconds.".format(end - start)
    #return r2_score(target.values, y_pred)
    return r2_score(target.values, y_pred), mean_absolute_error(target.values, y_pred)
    #return mean_squared_error(target.values, y_pred)


def train_predict(clf, X_train, y_train, X_test, y_test):
    ''' Train and predict using a classifer based on F1 score. '''
    
    # Indicate the classifier and the training set size
    print "Training a {} using a training set size of {}. . .".format(clf.__class__.__name__, len(X_train))
    
    # Train the classifier
    train_classifier(clf, X_train, y_train)
    
    # Print the results of prediction for both training and testing
    #print "R2 score for training set: {:.4f}.".format(predict_labels(clf, X_train, y_train))
    #print "R2 score for test set: {:.4f}.".format(predict_labels(clf, X_test, y_test))
    #print "MAE score for training set: {:.4f}.".format(predict_labels(clf, X_train, y_train))
    #print "MAE score for test set: {:.4f}.".format(predict_labels(clf, X_test, y_test))
    #print "MSE score for training set: {:.4f}.".format(predict_labels(clf, X_train, y_train))
    #print "MSE score for test set: {:.4f}.".format(predict_labels(clf, X_test, y_test))
    r2_1, mae_1 = predict_labels(clf, X_train, y_train)
    print "Score for training set; " + "R2: " + r2_1 + " " + "MAE: " + 
    
#clf = LinearRegression() # R2 0.4841
#clf = Ridge(random_state=42) # 0.4842
#clf = Lasso(random_state=42) # 0.4841
clf = ElasticNet(alpha=0.5, l1_ratio=0.75, random_state=42) # 0.4068
#clf = BayesianRidge() # 0.4843
#clf = ARDRegression() # Memory error

train_predict(clf, X_train, y_train, X_test, y_test)

Training a ElasticNet using a training set size of 150654. . .
Trained model in 10.2121 seconds
Made predictions in 0.0689 seconds.

ValueError: Unknown format code 'f' for object of type 'str'

In [6]:
# Search for optimal parameters
from sklearn.model_selection import GridSearchCV

# Parameters to do GridSearch on
cv_params = {
            'alpha': [1, 0.75, 0.5],
            'l1_ratio': [0.5, 0.25, 0.75]
            }

# Static model parameters
ind_params = {
            'random_state': 42
             }

# Initialize GridSearch with its parameters
optimized_SVC = GridSearchCV(estimator=ElasticNet(**ind_params), 
                             param_grid=cv_params, 
                             scoring='r2',
                             cv=5,
                             n_jobs=-1)

optimized_SVC.fit(X_train, y_train)
#optimized_ET.cv_results_
optimized_SVC.best_params_

{'alpha': 0.5, 'l1_ratio': 0.75}